server:
  applicationConnectors:
    - type: http
      port: 9000
    - type: https
      port: 9100
      keyStorePath: dropbookmarks.keystore
      keyStorePassword: p@ssw0rd
      validateCerts: false
logging:
  level: INFO
  loggers:
    com.udemy: DEBUG
password: "p@ssw0rd"

database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: singcontroller
  url: jdbc:mysql://localhost:3306/DropBookmarks

